### ISSUE TITLE
Find the cardinal, Discover a Deal

### ISSUE THREAD

**Issue by AdenaG** [Century21Stores/UX#6]
It will be 3 different gif assets of the bird (so we have options to place them in different places, and we can have solutions if there is any constraint visually). Jenn knows about this.
Once the bird is found and clicked, it will, somehow, reveal the deal. This depends on the strategy.
(Activate JMprototype = https://www.c21stores.com/pages/jmprototype)
https://www.c21stores.com/categories/shoes-boots

**Comment by AdenaG** [comment]
Feedback:
I like where it is now perched on a product on cat browse. If we are going to have it on pdp's or landing pages, I would suggest perching it on the you may also like or related products at the bottom.

Can we add an X to close out the lightbox or have it also close when you click out of it? When you click on it, it disappears. 

Questions: 
Is there any direction for how we are going to message customers about the game?

Whats the experience once a customer find the bird? Can they essentially go back to the same spot and keep getting the promo or tell all their friends exactly what item/category to go to? 

Can we add functionality to account for this, such as only having it appear one per session? Moving the placement on a regular basis would help.

**Comment by juanmriosv** [comment]
This still in very early prototype. Just for the visual part of it.
Seems the direction is going to change (fix on left window) will keep posted once is more clear.

**Comment by AdenaG** [comment]
Yep, sounds good. Thanks.

**Comment by juanmriosv** [comment]
Quick Prototype 2 on review (by Elisabeth):
Purpose: Elisabeth able to show a general idea on her meeting.

Again, this is a quick prototype, nothing has been discussed yet, but placement.

- Pollito appears fixed on the left bottom corner and once the user scrolls (point not specified yet)
- click on the bird and a window appears with the promotion.

**Comment by juanmriosv** [comment]
You can see it by activating Jmprototype Release
Since one of the categories is not available yet. I have place it in this two categories:

11/29: https://www.c21stores.com/categories/home-drinkware-barware
12/08: https://www.c21stores.com/categories/shoes-boots

**I built it base on the below information:**

**Location:**
11/29 - Home > Drinkware & barware category
12/8 - New + now > Fur salon

**Details**
11/29/2016
Email/social only
Online only
Free Shipping
Code: C21FREESHIP

12/8/2016
Email/social only
Online only
$10 off $100
Code: C2110OFF
One per customer

**Comment by c21hornak** [comment]
@AdenaG please QA

**Comment by c21hornak** [comment]
Closing.
